#!/bin/sh
#source ~/OpenFOAM/OpenFOAM-v1912/etc/bashrc
#cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication blockMesh
runApplication setFields
#runApplication $(getApplication)
runApplication decomposePar -constant
runParallel $(getApplication)
#runParallel postProcess -parallel -func devRhoReff
#runParallel postProcess -parallel -func outputSurfaceAvarageVelocity
#runApplication postProcess -func wallShearStress
#runApplication reconstructPar
#runApplication postProcess -func outputSurfaceIntegrateAlphaWater
#python3 calcOutputFlowHeight.py
#touch foam.foam
#~/Software/ParaView-5.9.0-MPI-Linux-Python3.8-64bit/bin/pvpython --force-offscreen-rendering pvScript.py
runParallel postProcess -parallel -func singleGraph
python3 calcLoss.py

#------------------------------------------------------------------------------
