#!/bin/sh
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication blockMesh
runApplication setFields
runApplication decomposePar -constant
runParallel $(getApplication)
runParallel postProcess -parallel -latestTime -func singleGraph
python3 calcLoss.py 2>&1 > log.calcLoss

#------------------------------------------------------------------------------
